spring.application.name: srv-producer-a
service-b:
  url: http://172.22.0.4:8080
spring:
  rabbitmq:
    username: guest
    password: guest
    host: 172.22.0.2
    port: 5672
resilience4j:
  circuitbreaker:
    instances:
      externalService:
        register-health-indicator: true
        failureRateThreshold: 40
        minimumNumberOfCalls: 10
        slowCallDurationThreshold: 1s
        slowCallRateThreshold : 40
        slidingWindowSize: 10
        slidingWindowType: count_based
        waitDurationInOpenState: 1m
        maxWaitDurationInHalfOpenState: 5m
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      externalService:
        timeoutDuration: 1200ms
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
